using System.Text;
using System.Text.Json;
using OutlookShredder.Proxy.Models;

namespace OutlookShredder.Proxy.Services;

/// <summary>
/// Calls Claude to classify a PDF as an ERP document and extract its structured data.
/// Uses tool-use for deterministic JSON output and prompt caching.
/// Separate from IAiExtractionService — ERP documents are outbound company records,
/// not inbound supplier quotes, and require a different extraction schema.
/// </summary>
public class ErpAiService
{
    private readonly IConfiguration _config;
    private readonly ILogger<ErpAiService> _log;
    private readonly AiRateLimitTracker _rateLimits;
    private readonly HttpClient _http;

    private const string ApiUrl = "https://api.anthropic.com/v1/messages";

    private const string SystemPromptText = """
        You are a document classification assistant for Metal Supermarkets Hackensack, a metals
        distribution company. You receive PDF files and must determine whether each was generated
        by the company ERP system, then extract its structured data.

        IDENTIFYING ERP DOCUMENTS
        ERP-generated documents are always outbound — issued BY Metal Supermarkets TO a customer.
        They always carry a reference number starting with:
          • HSK-  (Hackensack store prefix, e.g. HSK-INV-001234, HSK-QU-5678, HSK-SO-0099)
          • 020803-  (corporate prefix, e.g. 020803-INV-001234)
        The document will be on Metal Supermarkets letterhead and addressed to a customer.

        Document types and typical label text:
          Quotation    — "Quote", "Quotation" heading; no binding commitment
          SalesOrder   — "Sales Order", "Order Confirmation", "SO" in number
          Invoice      — "Invoice", "Tax Invoice", "INV" in number
          CreditNote   — "Credit Note", "Credit Memo", "CR" in number
          Payment      — "Receipt", "Payment Confirmation", "PAY" in number
          ShippingNote — "Delivery Note", "Packing Slip", "Dispatch Note", "SHP"/"DN" in number

        Return is_erp_document = false for:
          • Supplier invoices / quotes received FROM external companies
          • Bank statements, insurance documents, or any non-ERP file
          • Any PDF that lacks an HSK- or 020803- reference number

        DOCUMENT NUMBER
        Look for the primary ERP reference in the document header, e.g.:
          "Invoice No: HSK-INV-001234"   "Quotation: HSK-QU-5678"   "Order: 020803-SO-0099"
        Return the full number including its prefix.

        CUSTOMER INFORMATION
        Extract the customer name (company the document is addressed to) and any customer-assigned
        purchase order or reference number (e.g. "Customer PO: 12345", "Your Ref:", "Cust. Order:").

        LINE ITEMS
        For each product line extract: description (include grade, form, dimensions), product code
        if shown, quantity, unit (PC, FT, LB, etc.), unit price, and line total.

        TOTALS
        Extract the document grand total and currency (default USD if not stated).
        """;

    private static readonly JsonElement _toolJson = JsonDocument.Parse("""
        {
          "name": "record_erp_document",
          "description": "Record structured data extracted from a Metal Supermarkets ERP PDF.",
          "input_schema": {
            "type": "object",
            "required": ["is_erp_document"],
            "properties": {
              "is_erp_document":    { "type": "boolean",           "description": "true if generated by the Metal Supermarkets ERP (has HSK- or 020803- reference, issued to a customer)." },
              "document_type":      { "type": ["string","null"],   "enum": ["Quotation","SalesOrder","Invoice","CreditNote","Payment","ShippingNote","Unknown",null] },
              "document_number":    { "type": ["string","null"],   "description": "Full ERP reference, e.g. HSK-INV-001234 or 020803-SO-5678." },
              "customer_name":      { "type": ["string","null"],   "description": "Company the document is addressed to." },
              "customer_reference": { "type": ["string","null"],   "description": "Customer's own PO or reference number, if stated." },
              "document_date":      { "type": ["string","null"],   "description": "Date as printed on the document." },
              "total_amount":       { "type": ["string","null"],   "description": "Grand total as a numeric string, e.g. '1234.56'." },
              "currency":           { "type": ["string","null"],   "description": "Currency code, e.g. USD. Default USD." },
              "line_items": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "description": { "type": ["string","null"] },
                    "code":        { "type": ["string","null"] },
                    "quantity":    { "type": ["string","null"] },
                    "unit":        { "type": ["string","null"] },
                    "unit_price":  { "type": ["string","null"] },
                    "total_price": { "type": ["string","null"] }
                  }
                }
              },
              "notes": { "type": ["string","null"], "description": "Any other relevant notes or terms printed on the document." }
            }
          }
        }
        """).RootElement;

    private static readonly (int MinMs, int MaxMs)[] RetryDelays =
    [
        (2_000,  4_000),
        (5_000, 10_000),
        (15_000, 25_000),
    ];

    public ErpAiService(
        IConfiguration config,
        ILogger<ErpAiService> log,
        AiRateLimitTracker rateLimits,
        ILogger<AiRateLimitHandler> handlerLog)
    {
        _config     = config;
        _log        = log;
        _rateLimits = rateLimits;

        var timeoutSeconds = int.TryParse(_config["Claude:TimeoutSeconds"], out var t) ? t : 60;
        var handler = new AiRateLimitHandler("Claude", rateLimits, handlerLog)
        {
            InnerHandler = new HttpClientHandler()
        };
        _http = new HttpClient(handler) { Timeout = TimeSpan.FromSeconds(timeoutSeconds) };
    }

    /// <summary>
    /// Classifies the PDF and extracts its ERP data.
    /// Returns null on API failure. Returns an extraction with IsErpDocument=false for non-ERP PDFs.
    /// </summary>
    public async Task<ErpExtraction?> ExtractAsync(string base64Pdf, string fileName, CancellationToken ct = default)
    {
        var apiKey = _config["Anthropic:ApiKey"];
        if (string.IsNullOrEmpty(apiKey))
        {
            _log.LogWarning("[ERP] Anthropic:ApiKey not configured — skipping AI extraction");
            return null;
        }

        var maxTokens  = int.TryParse(_config["Claude:MaxTokens"],  out var mt) ? mt : 2048;
        var maxRetries = int.TryParse(_config["Claude:MaxRetries"], out var mr) ? mr : 3;
        var model      = _config["Claude:Model"] ?? "claude-sonnet-4-6";

        var userContent = new object[]
        {
            new {
                type   = "document",
                source = new { type = "base64", media_type = "application/pdf", data = base64Pdf },
                title  = fileName
            },
            new { type = "text", text = $"Classify and extract data from the attached PDF: {fileName}" }
        };

        var body = new
        {
            model,
            max_tokens  = maxTokens,
            system      = new object[]
            {
                new { type = "text", text = SystemPromptText, cache_control = new { type = "ephemeral" } }
            },
            tools       = new[] { _toolJson },
            tool_choice = new { type = "tool", name = "record_erp_document" },
            messages    = new[] { new { role = "user", content = userContent } }
        };

        var bodyJson = JsonSerializer.Serialize(body);
        HttpResponseMessage response;
        try
        {
            response = await SendWithRetryAsync(apiKey, bodyJson, maxRetries, ct);
        }
        catch (Exception ex)
        {
            _log.LogError(ex, "[ERP] Claude call failed for {File}", fileName);
            return null;
        }

        var raw = await response.Content.ReadAsStringAsync(ct);

        if (!response.IsSuccessStatusCode)
        {
            _log.LogError("[ERP] Claude API error {Status} for {File}: {Body}", response.StatusCode, fileName, raw);
            return null;
        }

        using var doc = JsonDocument.Parse(raw);
        var root      = doc.RootElement;

        if (root.TryGetProperty("stop_reason", out var stop) && stop.GetString() == "max_tokens")
            _log.LogWarning("[ERP] Claude hit max_tokens for {File} — response may be incomplete", fileName);

        if (!root.TryGetProperty("content", out var content)) return null;

        foreach (var block in content.EnumerateArray())
        {
            if (!block.TryGetProperty("type", out var typeEl) || typeEl.GetString() != "tool_use") continue;
            if (!block.TryGetProperty("name", out var nameEl) || nameEl.GetString() != "record_erp_document") continue;
            if (!block.TryGetProperty("input", out var inputEl)) continue;

            var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var extraction = JsonSerializer.Deserialize<ErpExtraction>(inputEl.GetRawText(), opts);
            if (extraction is not null)
                _log.LogInformation("[ERP] Claude: IsErp={IsErp} Type={Type} Number={Number} File={File}",
                    extraction.IsErpDocument, extraction.DocumentType, extraction.DocumentNumber, fileName);
            return extraction;
        }

        _log.LogWarning("[ERP] Claude returned no record_erp_document block for {File}", fileName);
        return null;
    }

    private async Task<HttpResponseMessage> SendWithRetryAsync(
        string apiKey, string bodyJson, int maxRetries, CancellationToken ct)
    {
        HttpResponseMessage? last = null;

        for (int attempt = 0; attempt <= maxRetries; attempt++)
        {
            await _rateLimits.ThrottleIfNeededAsync("Claude", ct);

            var req = new HttpRequestMessage(HttpMethod.Post, ApiUrl);
            req.Headers.Add("x-api-key", apiKey);
            req.Headers.Add("anthropic-version", "2023-06-01");
            req.Headers.Add("anthropic-beta", "prompt-caching-2024-07-31");
            req.Content = new StringContent(bodyJson, Encoding.UTF8, "application/json");

            try
            {
                last = await _http.SendAsync(req, ct);
            }
            catch (Exception ex) when (attempt < maxRetries)
            {
                _log.LogWarning(ex, "[ERP] Claude attempt {A}/{T} threw — retrying", attempt + 1, maxRetries + 1);
                await DelayAsync(attempt, ct);
                continue;
            }

            if (last.IsSuccessStatusCode) return last;

            var status = (int)last.StatusCode;
            if ((status == 429 || status >= 500) && attempt < maxRetries)
            {
                _log.LogWarning("[ERP] Claude {Status} attempt {A}/{T} — retrying", status, attempt + 1, maxRetries + 1);
                await DelayAsync(attempt, ct);
                continue;
            }

            return last;
        }

        return last!;
    }

    private async Task DelayAsync(int attempt, CancellationToken ct)
    {
        var (min, max) = RetryDelays[Math.Min(attempt, RetryDelays.Length - 1)];
        await Task.Delay(Random.Shared.Next(min, max), ct);
    }
}
